function saveDataToFile() {

    let fullDocument = [];

    VATNumber = document.getElementById("VATNumber").value;
    firstDateThisYear = document.getElementById("firstDateThisYear").value;
    lastDateThisYear = document.getElementById("lastDateThisYear").value;
    firstDateLastYear = document.getElementById("firstDateLastYear").value;
    lastDateLastYear = document.getElementById("lastDateLastYear").value;

    fullDocument.push('<?xml version="1.0" encoding="UTF-8"?>')
    fullDocument.push('<!--Generated by K-Revision-->')
    fullDocument.push('<?instance-generator id="K-Revision XBRL Generator" version="2020.01" creationdate="' + returnDate() + '"?>')
    fullDocument.push('<xbrli:xbrl xml:lang="fo" xmlns:iso4217="http://www.xbrl.org/2003/iso4217" xmlns:cmn="http://xbrl.dcca.dk/cmn" xmlns:sob="http://xbrl.dcca.dk/sob" xmlns:fo-tax="http://www.xbrl.gov.fo/tax" xmlns:gsd="http://xbrl.dcca.dk/gsd" xmlns:fsa="http://xbrl.dcca.dk/fsa" xmlns:fo-cro="http://www.xbrl.gov.fo/cro" xmlns:xbrli="http://www.xbrl.org/2003/instance" xmlns:link="http://www.xbrl.org/2003/linkbase" xmlns:xbrldi="http://xbrl.org/2006/xbrldi" xmlns:xlink="http://www.w3.org/1999/xlink">')
    fullDocument.push('<link:schemaRef xlink:type="simple" xlink:href="https://www.vinnugluggin.fo/taxonomy/20180301/entryFODanishGAAPBalanceSheetAccountFormIncomeStatementByNatureIncludingManagementsReview20161001.xsd"/>')
    fullDocument.push('<xbrli:unit id="DKK"><xbrli:measure>iso4217:DKK</xbrli:measure></xbrli:unit>')
    
    //fullDocument.push('<xbrli:measure>' + userInput + '</xbrli:measure>')

    function documentToString() {
        let fullDocumentString = '';
        for(i = 0; i < fullDocument.length; i++) {
            fullDocumentString = fullDocumentString + fullDocument[i];
        }

        return fullDocumentString
    }

    let fullString = documentToString();

    let blob = new Blob([fullString], { type: "text/plain;charset=utf-8" });
    saveAs(blob, "dynamic.xml");
}